### ISSUE TITLE
Bundling with android-build-tools

### ISSUE THREAD

**Issue by ichan-mb** [fuse-open/fuse-sdk#2]
Since `fuse-sdk` now is the easiest way for trying FuseOpen Framework for new and existing users, it would be nice if we also bundling it with [android-build-tools](https://github.com/mortend/android-build-tools) so users (especially the new one) can get quickly up and running on their first Android app

**Comment by mortend** [comment]
That's a good idea!

The problem is that `android-build-tools` is a large download that takes a long time to install.

I think another option is to print a message to the user in Terminal after installing `fuse-sdk`, to inform about `android-build-tools` and show the command to install it. I think we can use install hooks in NPM to implement this.

**Comment by ichan-mb** [comment]
Yess.. I think that informing users to install `android-build-tools` is a better solution. And you are already done that 👍

I am closing this issue.. thanks 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
